name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa66e532fdcf36bc54d6a34824d2d4780e5c718980dfdf64be99aa7a44bb545d"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
