name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c93ccc05b4a17d95cc834323e7605d22ef6b1fd9aabae18276b009dcb169d8df"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
