name = "Uncle Al's Fat Stash"
author = "Pulp Star"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cce6813e1b0809e369d0e19cab52cbce242a967dfb9a1f72e4e81164a3c8e2fa"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"
